#!/bin/bash

if [ -z "$HUGO_ENV" ]; then
    export HUGO_ENV=development
fi

WORKDIR=$(pwd)
cd /tmp/src
[ -d public ] && rm -rf public

if [ "$HUGO_ENV" == "production" ]; then

  if [ -z "$HUGO_UPDATE_MODULE" ]; then
    echo "---> Keep current version of hugo module"
  else
    echo "---> Update hugo module to the last commit"
    hugo mod get -u
  fi


  echo "---> Generating hugo content"
  hugo

  if [ -z "$RUN_SCRIPT" ]
  then
      echo "---> No user script to run"
  else
      echo "---> Start run user script"

      IFS=';'
      read -a strarr <<< "$RUN_SCRIPT"

      for val in "${strarr[@]}";
      do
          chmod +x "$PWD/$val"
          bash -c "$PWD/$val $PWD/public"
      done
  fi;

  echo "---> Move hugo content"
  cd $WORKDIR
  mv /tmp/src/public/* .

else

  echo "---> Move hugo content"
  cd $WORKDIR
  mv /tmp/src/* .

fi